### ISSUE TITLE
missing lipencoder module config file: lrw_snv1x_tcn2x.json

### ISSUE THREAD

**Issue by CircleRedRain** [Sreyan88/LipGER#1]
it seems that I can not find it in google driver, and where can i find it?

self.visual_net_lipreading = self.build_lipencoder("/path/to/lrw_snv1x_tcn2x.json")

**Comment by Sreyan88** [comment]
Thank You for pointing this out. I have uploaded it here:

https://drive.google.com/file/d/1ThwVQdRkYavLzY6seM7N_qV3S1RYeXjN/view?usp=sharing
